name: Apateonos
permalink: :2021/:Jan/:18/:Apateonos.log
baseurl: /jekyll-theme-diary

# Your blog's start year and this year, showed in the footer left
# start is optional
start: 2017
now: 2019
 
# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  email : apateonos@gmail.com
  github : https://github.com/apateonos
  twitter : null

# Links in the navigation, you can modify both link name and link url
nav:
   Home: "http://apateonos.github.io"
   Diary: "http://apateonos.github.io/diary"

   
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed